name: Test and Lint on frontend

on:
  push:
    paths:
      - 'frontend/**'

defaults:
  run:
    working-directory: frontend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run Test
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
