name: scraping book record

on:
  schedule:
    # Run jobs every day at 3:00
    - cron: '0 18 * * *'

defaults:
  run:
    working-directory: batch/scraping

jobs:
  scraping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup chromedriver
        uses: nanasess/setup-chromedriver@v2
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: build with Gradle
        run: ./gradlew build
      - name: run with Gradle and generate json
        run: ./gradlew run --args="739784 book-list.json only-diff"
      - name: setup git
        run: |
          git config --local user.email "130679205+okaryo-bot[bot]@users.noreply.github.com"
          git config --local user.name "OKARYO BOT[bot]"
          git config --local pull.rebase false
      - name: detect any diff
        run: |
          if ! git diff --exit-code --quiet
          then
            echo existsDiff=true >> $GITHUB_ENV
          else
            echo existsDiff=false >> $GITHUB_ENV
          fi
      - name: git commit and push if any changes
        if: env.existsDiff == 'true'
        run: |
          git add .
          git commit -m "update: reading records by scheduled task"
          git pull
          git push origin main
        working-directory: ./
