name: scraping book record

on:
  schedule:
    # Run jobs every day at 3:00
    - cron: '0 18 * * *'

defaults:
  run:
    working-directory: batch/scraping

jobs:
  scraping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup chromedriver
        run: |
          MAJOR_CHROME_VERSION=$(google-chrome --version | sed -r 's/^[^0-9]*([0-9]*).*$/\1/g')
          LATEST_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$MAJOR_CHROME_VERSION)
          curl https://chromedriver.storage.googleapis.com/$LATEST_VERSION/chromedriver_linux64.zip --output ./chromedriver_linux64.zip
          echo y | unzip chromedriver_linux64.zip
      - name: setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: build with Gradle
        run: ./gradlew build
      - name: run with Gradle and generate json
        run: ./gradlew run --args="739784 book-list.json only-diff"
      - name: setup git
        run: |
          git config --local user.email "okaryotr@gmail.com"
          git config --local user.name "okaryo"
          git config --local pull.rebase false
      - name: detect any diff
        run: |
          if ! git diff --exit-code --quiet
          then
            echo existsDiff=true >> $GITHUB_ENV
          else
            echo existsDiff=false >> $GITHUB_ENV
          fi
      - name: git commit and push if any changes
        if: env.existsDiff == 'true'
        run: |
          git add .
          git commit -m "[add] Generated File By Scheduled Task"
          git pull
          git push origin main
        working-directory: ./
