name: Test and Lint

'on':
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
          cache: npm
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install dependencies
        run: npm ci
      - name: Run Test
        run: npm run test
      - name: Run Lint
        run: npm run lint
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install dependencies
        run: npm ci
      - name: Run Test
        run: npm run test
      - name: Run Lint
        run: npm run lint
